### ISSUE TITLE
Info on usage

### ISSUE THREAD

**Issue by docop** [cqtrade/infobot#1]
Hi So your project look interesting, but i<m not quite sure about how can we make it run..  Do you may have a small wiki for it ?
Thanks and happy new year -no covid

**Comment by reposandermets** [comment]
Hey, @docop 

Currently, this app is receiving signals from Tradingview and taking positions in ftx.com. It also logs signals to Discord.

There's one signal built-in now to detect local bottoms, but it's not active. So business logic comes from Tradingview.

Could you share your use case? 

.env has to be set to run it.

```
DISCORD_ENABLED=
HEALTH_LOG_ENABLED=
DISCORD_CH_RANDOM_IDEAS=...
DISCORD_CH_ALTSIGNALS=...
DISCORD_CH_FLASH=...
DISCORD_CH_HEALTH=...
DISCORD_CH_LOGS=...
FTX_KEY=...
FTX_SECRET=...
POSITION_SIZE=
PROFIT_PERCENTAGE=0.05
SERVER_URL=0.0.0.0:8080
HEALTH_REPORT_SECONDS=21
FUTURE_ARB_BTC=BTC-0325
FUTURE_ARB_ETH=ETH-0325
FUTURE_BTC=BTC-0325
FUTURE_ETH=ETH-0325
SUBA_BTCDC=btcdc
SUBA_ETHDC=ethdc
RISKDC=3

TA_RSI_PERIOD=14
TA_ROC_PERIOD=9
TA_NTDF_LOOKBACK=33
TA_NTDFSMOOTHED_PERIOD=33
TA_MFI_PERIOD=3
TA_RSI_LOW=25.0
TA_MFI_LOW=10.0
TA_ROC_LOW=-11.0
TA_FILTER_LOW=-0.01
TA_FILTER_HIGH=0.55
````

**Comment by docop** [comment]
So it will work by getting info via the websocket from tv api ?  I was looking at more the discord info and not the ftx direct position.

**Comment by reposandermets** [comment]
From websocket connection, it gets info from FTX.com
In the TV there's an alert set that sends out info in JSON format.
